name: Build and deploy container app to Azure Web App - petfeederapii

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_a4f182f7653f49e789b5205c06dd30dc }}
          password: ${{ secrets.AzureAppService_ContainerPassword_7c21a47a7b2646f690e8c17346e5b7da }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a4f182f7653f49e789b5205c06dd30dc }}/kokas340/petfeederapi:${{ github.sha }}
          file: ./Cloud/Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'petfeederapii'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_072f20ba1c834fa9978db6f8dcb2bb10 }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a4f182f7653f49e789b5205c06dd30dc }}/kokas340/petfeederapi:${{ github.sha }}'
