name: DEV BRANCH DOCKER

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Spring Boot JAR
        run: mvn -B clean package --file Cloud/pom.xml

      - name: Print Contents of Target Directory
        run: ls -R Cloud/target

      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_CLOUD }}
          password: ${{ secrets.DOCKERHUB_TOKEN_CLOUD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: Cloud
          push: true
          tags: kokas340/petfeederapi:latest

