name: Node.js CI & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./Fronted/pet-feeder/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./Fronted/pet-feeder

      - name: Build
        run: npm run build --if-present
        working-directory: ./Fronted/pet-feeder

      - name: Test
        run: npm test
        working-directory: ./Fronted/pet-feeder

      - name: List Build Directory Contents
        run: ls -R ./Fronted/pet-feeder/build

  deploy:
    runs-on: ubuntu-latest

    needs: build  # Ensure that the build job completes before starting the deploy job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: npm run deploy
        env:
          CI: false  # Disable CI for Create React App

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Fronted/pet-feeder/build  # Adjust the path based on your build directory
