# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cloudpetfeederapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3d1cceeb2b27478b8e08baff5d1dfcf0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a5de0b01d55418894b168945d1de31a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3d1cceeb2b27478b8e08baff5d1dfcf0 }}/kokas340/petfeederapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cloudpetfeederapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bd2f04fc69ff42a98892a4444a48032f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3d1cceeb2b27478b8e08baff5d1dfcf0 }}/kokas340/petfeederapi:${{ github.sha }}'