# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code, run tests, and deploy to GitHub Pages on the "main" branch
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD v2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./Fronted/pet-feeder/package-lock.json

    - name: Install Dependencies
      run: npm install
      working-directory: ./Fronted/pet-feeder

    - name: Build
      run: npm run build --if-present
      working-directory: ./Fronted/pet-feeder

    - name: Test
      run: npm test
      working-directory: ./Fronted/pet-feeder

    - name: Deploy to GitHub Pages
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B gh-pages
          git rm -r .
          cp -r ./Fronted/pet-feeder/build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch
          git remote -v
          git status
          git remote show origin
          git push origin gh-pages
      

